# Generated by Django 3.1.2 on 2020-10-09 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='desription',
            new_name='description',
        ),
    ]
